name: automerge
on:
  label: 
    types:
      - Daily Check-in
  schedule:
    - cron: "*/15 * * * *"
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.9.0
        if: github.actor == 'liuhaoyang'
        with:
          args: "--trace"
        env:
          GITHUB_TOKEN: "${{ secrets.MERGE_TOKEN }}"
          MERGE_METHOD: "squash"
          MERGE_LABELS: ""
          MERGE_COMMIT_MESSAGE: "Auto Merge"
